// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rrocksdb_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// regexMatch
bool regexMatch(std::string s, std::string m);
RcppExport SEXP _rrocksdb_regexMatch(SEXP sSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(regexMatch(s, m));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_rrocksdb();

static const R_CallMethodDef CallEntries[] = {
    {"_rrocksdb_regexMatch", (DL_FUNC) &_rrocksdb_regexMatch, 2},
    {"_rcpp_module_boot_rrocksdb", (DL_FUNC) &_rcpp_module_boot_rrocksdb, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rrocksdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
