// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rrocksdb_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// regexMatch
bool regexMatch(std::string s, std::string m);
RcppExport SEXP rrocksdb_regexMatch(SEXP sSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type m(mSEXP);
    __result = Rcpp::wrap(regexMatch(s, m));
    return __result;
END_RCPP
}
