# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title C++ regex_match wrapper
#' @name regexMatch
#' @return string
#' @examples
#' regexMatch("1:2:last_name", "(.*):(.*):last_name")
regexMatch <- function(s, m) {
    .Call('_rrocksdb_regexMatch', PACKAGE = 'rrocksdb', s, m)
}

