# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrocksdb_new <- function(name) {
    .Call('rrocksdb_rrocksdb_new', PACKAGE = 'rrocksdb', name)
}

rrocksdb_put <- function(r, key, value) {
    .Call('rrocksdb_rrocksdb_put', PACKAGE = 'rrocksdb', r, key, value)
}

rrocksdb_get <- function(r, key) {
    .Call('rrocksdb_rrocksdb_get', PACKAGE = 'rrocksdb', r, key)
}

rrocksdb_delete <- function(r, key) {
    .Call('rrocksdb_rrocksdb_delete', PACKAGE = 'rrocksdb', r, key)
}

